CREATE VIEW VIEW_DS_MUON_SACH
AS
SELECT SM.ID_SACH,TUA, STT, LAN AS LANXB,SM.SOTHE, DG.TEN, PHAI, NGAYMUON, TINHTRANG
FROM (SELECT SOTHE, ID_SACH, NGAYMUON, TINHTRANG=N'Chưa trả' FROM SachMuon WHERE NGAYTRA IS NULL) SM,
(SELECT SOTHE, TEN, PHAI FROM DocGia) DG, (SELECT ID_SACH, STT, MASACHXB FROM SachTV) STV,
(SELECT MASACHXB, LAN, MASACH FROM SachXB) SXB, (SELECT MA,TUA FROM TaiLieu WHERE LOAI=N'Sách') S
WHERE SM.SOTHE=DG.SOTHE AND SM.ID_SACH=STV.ID_SACH 
AND STV.MASACHXB=SXB.MASACHXB AND SXB.MASACH=S.MA
GO
CREATE VIEW VIEW_DS_MUON_BAO
AS
SELECT BM.ID_BAO, TUA, LAN AS LANXB, BM.SOTHE, TEN, PHAI, NGAYMUON, TINHTRANG
FROM (SELECT MA, TUA FROM TaiLieu WHERE LOAI=N'Báo') B,
(SELECT ID_BAO, MABAO, LAN FROM BaoTV) BTV, 
(SELECT SOTHE, ID_BAO, NGAYMUON, TINHTRANG=N'Chưa trả' FROM BaoMuon WHERE NGAYTRA IS NULL) BM,
(SELECT SOTHE,TEN, PHAI FROM DocGia) DG
WHERE BM.SOTHE=DG.SOTHE AND BM.ID_BAO = BTV.ID_BAO AND BTV.MABAO=B.MA
GO

CREATE VIEW VIEW_SACH_DANGMUON
AS
SELECT SM.ID_SACH, TUA, LAN AS LANXB, STT, NGAYMUON, TINHTRANG=N'Chưa trả'
FROM (SELECT ID_SACH, NGAYMUON FROM SachMuon WHERE SOTHE=CONVERT(BIGINT,(SELECT NAME FROM sys.sysusers WHERE sid = SUSER_SID(SYSTEM_USER))) AND NGAYTRA IS NULL) SM,
(SELECT ID_SACH, STT, MASACHXB  FROM SachTV) STV, (SELECT MASACHXB, LAN, MASACH FROM SachXB)SXB,
(SELECT MA, TUA FROM TaiLieu WHERE LOAI=N'Sách') S
WHERE SM.ID_SACH=STV.ID_SACH AND STV.MASACHXB=SXB.MASACHXB AND SXB.MASACH=S.MA
GO
GRANT SELECT ON VIEW_SACH_DANGMUON TO DocGia
GO
DENY SELECT, INSERT,DELETE, UPDATE ON VIEW_SACH_DANGMUON TO QUANLY
GO
CREATE VIEW VIEW_BAO_DANGMUON
AS
SELECT BM.ID_BAO, TUA, LAN AS LANXB, NGAYMUON, TINHTRANG=N'Chưa trả'
FROM (SELECT ID_BAO, NGAYMUON FROM BaoMuon WHERE SOTHE=CONVERT(BIGINT,(SELECT NAME FROM sys.sysusers WHERE sid = SUSER_SID(SYSTEM_USER))) AND NGAYTRA IS NULL) BM,
(SELECT ID_BAO, MABAO, LAN FROM BaoTV) BTV, (SELECT MA,TUA FROM TaiLieu WHERE LOAI=N'Báo')B
WHERE BM.ID_BAO=BTV.ID_BAO AND BTV.MABAO=B.MA
GO
GRANT SELECT ON VIEW_BAO_DANGMUON TO DocGia
GO
DENY SELECT, INSERT,DELETE, UPDATE ON VIEW_BAO_DANGMUON TO QUANLY
GO

CREATE PROC SP_TimDocGia
@SOTHE BIGINT
AS
BEGIN
SELECT * FROM DocGia WHERE SOTHE=@SOTHE
END
GO