USE ThuVien
GO
CREATE INDEX IX_NGAYTRA ON SachMuon (NGAYTRA ASC)
GO
CREATE INDEX IX_NGAYTRA ON BaoMuon (NGAYTRA ASC)
GO
CREATE INDEX IX_SACH ON TaiLieu (LOAI DESC) 
GO
CREATE INDEX IX_BAO ON TaiLieu (LOAI ASC)
GO
CREATE INDEX IX_MABAO ON BaoTV (MABAO ASC)
GO

ALTER VIEW [dbo].[VIEW_BAOTV]
AS
SELECT ID_BAO, B.TUA, LANPH, NAMPH, DINHKY, NSX, SLTON
FROM (SELECT MA,TUA FROM TaiLieu WITH (INDEX=IX_BAO) WHERE LOAI=N'Báo') B, (SELECT MABAO,NAMPH,DINHKY,NSX FROM BaoPH) BPH,
(SELECT ID_BAO, MABAO, LAN AS LANPH, SLTON FROM BaoTV WITH (INDEX=IX_MABAO)) BTV
WHERE B.MA=BTV.MABAO AND B.MA=BPH.MABAO
GO

ALTER VIEW [dbo].[VIEW_SACHTV]
AS
SELECT ID_SACH, STT, S.TUA, TACGIA=STRING_AGG(TG.TEN,' '), LAN AS LANXB, NAM, NHAXB, CD, GIA, TINHTRANG, MUON
FROM (SELECT ID_SACH,STT,MASACHXB, TINHTRANG, 
MUON=(CASE WHEN (EXISTS(SELECT * FROM SachMuon SM WITH (INDEX=IX_NGAYTRA) WHERE STV.ID_SACH=SM.ID_SACH AND NGAYTRA IS NULL)) THEN N'Đang mượn'
ELSE N'Chưa mượn' END) 
FROM SachTV STV) STV, 
(SELECT MASACHXB, LAN, MASACH, NAM, NHAXB, CD,GIA FROM SachXB) SXB, (SELECT MA, TUA FROM TaiLieu WITH(INDEX=IX_SACH) WHERE LOAI=N'Sách') S,
(SELECT * FROM ChiTietTacGia) CTTG, (SELECT MATG, TEN FROM TacGia) TG
WHERE STV.MASACHXB=SXB.MASACHXB AND S.MA=SXB.MASACH AND CTTG.MASACH=S.MA AND CTTG.MATG=TG.MATG
GROUP BY ID_SACH, STT, S.TUA,LAN, NAM, NHAXB, CD,GIA, TINHTRANG, MUON
GO
ALTER VIEW VIEW_DS_MUON_SACH
AS
SELECT SM.ID_SACH,TUA, STT, LAN AS LANXB,SM.SOTHE, DG.TEN, PHAI, NGAYMUON, TINHTRANG=N'Chưa trả'
FROM (SELECT SOTHE, ID_SACH, NGAYMUON FROM SachMuon WITH (INDEX=IX_NGAYTRA) WHERE NGAYTRA IS NULL) SM,
(SELECT SOTHE, TEN, PHAI FROM DocGia) DG, (SELECT ID_SACH, STT, MASACHXB FROM SachTV) STV,
(SELECT MASACHXB, LAN, MASACH FROM SachXB) SXB, (SELECT MA,TUA FROM TaiLieu WITH(INDEX=IX_SACH) WHERE LOAI=N'Sách') S
WHERE SM.SOTHE=DG.SOTHE AND SM.ID_SACH=STV.ID_SACH 
AND STV.MASACHXB=SXB.MASACHXB AND SXB.MASACH=S.MA
GO
ALTER VIEW VIEW_DS_MUON_BAO
AS
SELECT BM.ID_BAO, TUA, LAN AS LANXB, BM.SOTHE, TEN, PHAI, NGAYMUON, TINHTRANG=N'Chưa trả'
FROM (SELECT MA, TUA FROM TaiLieu WITH(INDEX=IX_BAO) WHERE LOAI=N'Báo') B,
(SELECT ID_BAO, MABAO, LAN FROM BaoTV) BTV, 
(SELECT SOTHE, ID_BAO, NGAYMUON FROM BaoMuon WITH(INDEX=IX_NGAYTRA) WHERE NGAYTRA IS NULL) BM,
(SELECT SOTHE,TEN, PHAI FROM DocGia) DG
WHERE BM.SOTHE=DG.SOTHE AND BM.ID_BAO = BTV.ID_BAO AND BTV.MABAO=B.MA
GO

ALTER VIEW VIEW_SACH_DANGMUON
AS
SELECT SM.ID_SACH, TUA, LAN AS LANXB, STT, NGAYMUON, TINHTRANG=N'Chưa trả'
FROM (SELECT ID_SACH, NGAYMUON FROM SachMuon WITH(INDEX=IX_NGAYTRA) WHERE SOTHE=CONVERT(BIGINT,(SELECT NAME FROM sys.sysusers WHERE sid = SUSER_SID(SYSTEM_USER))) AND NGAYTRA IS NULL) SM,
(SELECT ID_SACH, STT, MASACHXB  FROM SachTV) STV, (SELECT MASACHXB, LAN, MASACH FROM SachXB)SXB,
(SELECT MA, TUA FROM TaiLieu WITH(INDEX=IX_SACH) WHERE LOAI=N'Sách') S
WHERE SM.ID_SACH=STV.ID_SACH AND STV.MASACHXB=SXB.MASACHXB AND SXB.MASACH=S.MA
GO

ALTER VIEW VIEW_BAO_DANGMUON
AS
SELECT BM.ID_BAO, TUA, LAN AS LANXB, NGAYMUON, TINHTRANG=N'Chưa trả'
FROM (SELECT ID_BAO, NGAYMUON FROM BaoMuon WITH(INDEX=IX_NGAYTRA) WHERE SOTHE=CONVERT(BIGINT,(SELECT NAME FROM sys.sysusers WHERE sid = SUSER_SID(SYSTEM_USER))) AND NGAYTRA IS NULL) BM,
(SELECT ID_BAO, MABAO, LAN FROM BaoTV) BTV, (SELECT MA,TUA FROM TaiLieu WITH(INDEX=IX_BAO) WHERE LOAI=N'Báo')B
WHERE BM.ID_BAO=BTV.ID_BAO AND BTV.MABAO=B.MA
GO

-- nếu lần đầu tạo view chạy lệnh này, dùng ctr + K + U để mở
--GRANT SELECT ON VIEW_SACH_DANGMUON TO DocGia
--GO
--DENY SELECT, INSERT,DELETE, UPDATE ON VIEW_SACH_DANGMUON TO QUANLY
--GO
--GRANT SELECT ON VIEW_BAO_DANGMUON TO DocGia
--GO
--DENY SELECT, INSERT,DELETE, UPDATE ON VIEW_BAO_DANGMUON TO QUANLY
--GO